/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DoAnUngDungMang;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
//import java.util.Scanner;

/**
 *
 * @author DELL
 */
public class Client extends javax.swing.JFrame {
    private  String host;
    private  int port;
    private  int bufferSize;
    public boolean flag=true;//biến cờ để chạy ngưng chương trình cho đến khi nhập input tiếp theo
    /**
     * Creates new form Client
     */
     public Client(String host, int port, int bufferSize){
        initComponents();
        this.host = host;
        this.port = port;
        this.bufferSize = bufferSize;
    }
     
    public Client() {
        initComponents();
    }
    public void start(String diadiem){
        try(DatagramSocket socket = new DatagramSocket()){
            socket.setSoTimeout(5000); // đặt thời gian timeout cho receive là 5s
            InetAddress address = InetAddress.getByName(host);
            while(flag){
                
                sendData(socket, address, diadiem);
              
                String receivedData = receiveData(socket); // nên bắt SocketTimeoutException ở đây
                System.out.println("Client nhận: " + receivedData);
                String [] parts =receivedData.split("/");
                
                updateThoiTiet(parts[0],parts[1],parts[2],parts[3],parts[4]);
                flag=false;//ngưng lại chờ đến khi ấn nút tìm kiếm nữa
            }
        }catch(IOException e){
            System.err.println(e.getMessage());
        }
    }

    // Gửi dữ liệu đến Server
    private void sendData(DatagramSocket socket, InetAddress address, String input) throws IOException {
        byte[] dataBytes = input.getBytes(StandardCharsets.UTF_8);
        DatagramPacket packet = new DatagramPacket(dataBytes, dataBytes.length, address, port);
        socket.send(packet);
    }
    // Nhận dữ liệu từ Server
    private String receiveData(DatagramSocket socket) throws IOException {
        DatagramPacket packet = new DatagramPacket(new byte[bufferSize], bufferSize);
        socket.receive(packet);
        byte[] dataBytes = Arrays.copyOf(packet.getData(), packet.getLength());
        return new String(dataBytes, StandardCharsets.UTF_8);
    }
     public void updateThoiTiet(String diachi,String time, String csuv, String temper, String humidity ){
         ResultCity x=new ResultCity();
         x.setVisible(true);
         this.setVisible(false);
         x.setThoiTiet(diachi,time,csuv,temper,humidity);
     }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainlayout = new javax.swing.JPanel();
        inputvitri = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(600, 280));

        Mainlayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputvitri.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputvitri.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputvitri.setText("Hãy nhập địa danh bạn muốn tra cứu");
        inputvitri.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputvitri.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputvitri.setFocusable(false);
        inputvitri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputvitriMouseClicked(evt);
            }
        });
        inputvitri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputvitriActionPerformed(evt);
            }
        });
        Mainlayout.add(inputvitri, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 420, 50));

        title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        title.setText("ỨNG DỤNG TRA CỨU THÔNG TIN VỀ ĐỊA ĐIỂM DU LỊCH");
        Mainlayout.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5-cach-quang-ba-du-lich.jpg"))); // NOI18N
        Mainlayout.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 800, 390));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-magnifying-glass-30.png"))); // NOI18N
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        Mainlayout.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Mainlayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mainlayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void inputvitriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputvitriMouseClicked
        // TODO add your handling code here:
        inputvitri.setText("");
        inputvitri.setFocusable(true);
        inputvitri.requestFocusInWindow();
    }//GEN-LAST:event_inputvitriMouseClicked

    private void inputvitriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputvitriActionPerformed
        // TODO add your handling code here:
        search.doClick();
    }//GEN-LAST:event_inputvitriActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        String diadiem = inputvitri.getText();
        Client client = new Client("127.0.0.1", 1234, 1024);
        client.start(diadiem);
        dispose();
        flag=true;
    }//GEN-LAST:event_searchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mainlayout;
    private javax.swing.JLabel image;
    private javax.swing.JTextField inputvitri;
    private javax.swing.JButton search;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
