/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DoAnUngDungMang;

import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class PanelResult extends javax.swing.JPanel {

    /**
     * Creates new form 
     */
    
    
    /*public void updateViTri(String input){
        
        toado.setText("Tọa độ: "+parts[5]+" độ Vĩ Bắc, "+parts[6]+" độ Kinh Đông");
    }*/
    
    public void updateThoiTiet(String input){
        String[] parts=input.split("//");
        /*for(int i=0;i<7;i++){
            System.out.println("parts["+i+"]:"+parts[i]);
        }*/
        title.setText("KẾT QUẢ TÌM KIẾM: "+parts[0]);
        thoigian.setText("Thời gian đo đạt: "+parts[1]);
        uv.setText("Chỉ số UV :" + parts[2]);
        nhietdo.setText("Nhiệt độ: "+parts[3]);
        doam.setText("Độ ẩm: "+parts[4]);
        toado.setText("Tọa độ: "+parts[5]+" độ Vĩ Bắc, "+parts[6]+" độ Kinh Đông");
    }
    
    public void updateKhachSan(String input){
        String[] parts=input.split("/");
        Object[] row = {parts[0],parts[1],parts[2],parts[3]};
        DefaultTableModel model = (DefaultTableModel) danhsachHotel.getModel();
        model.addRow(row);
        
    }
    public PanelResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        ThongTinDiaLy = new javax.swing.JPanel();
        danso = new javax.swing.JLabel();
        toado = new javax.swing.JLabel();
        quocgia = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ThoiTiet = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        thoigian = new javax.swing.JLabel();
        uv = new javax.swing.JLabel();
        nhietdo = new javax.swing.JLabel();
        doam = new javax.swing.JLabel();
        newpapers = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        KhachSan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhsachHotel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("KẾT QUẢ TÌM KIẾM:");

        ThongTinDiaLy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        danso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        danso.setText("Dân số:");

        toado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toado.setText("Tọa độ: ");

        quocgia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quocgia.setText("Quốc gia: ");

        title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title1.setText("THÔNG TIN ĐỊA LÝ:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Vị trí: ");

        javax.swing.GroupLayout ThongTinDiaLyLayout = new javax.swing.GroupLayout(ThongTinDiaLy);
        ThongTinDiaLy.setLayout(ThongTinDiaLyLayout);
        ThongTinDiaLyLayout.setHorizontalGroup(
            ThongTinDiaLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinDiaLyLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ThongTinDiaLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ThongTinDiaLyLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(ThongTinDiaLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(danso)
                            .addComponent(quocgia)
                            .addComponent(toado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThongTinDiaLyLayout.setVerticalGroup(
            ThongTinDiaLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinDiaLyLayout.createSequentialGroup()
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(quocgia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(danso)
                .addGap(6, 6, 6))
        );

        ThoiTiet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        title2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title2.setText("THỜI TIẾT HIỆN TẠI: ");

        thoigian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thoigian.setText("Thời gian : ");

        uv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uv.setText("Chỉ số UV :");

        nhietdo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nhietdo.setText("Nhiệt độ: ");

        doam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doam.setText("Độ ẩm: ");

        javax.swing.GroupLayout ThoiTietLayout = new javax.swing.GroupLayout(ThoiTiet);
        ThoiTiet.setLayout(ThoiTietLayout);
        ThoiTietLayout.setHorizontalGroup(
            ThoiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThoiTietLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ThoiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thoigian)
                    .addComponent(uv)
                    .addComponent(nhietdo)
                    .addComponent(doam)
                    .addComponent(title2))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        ThoiTietLayout.setVerticalGroup(
            ThoiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThoiTietLayout.createSequentialGroup()
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thoigian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhietdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newpapers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tiêu đề bài báo", "Đường dẫn"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("MỘT SỐ BÀI BÁO LIÊN QUAN:");

        javax.swing.GroupLayout newpapersLayout = new javax.swing.GroupLayout(newpapers);
        newpapers.setLayout(newpapersLayout);
        newpapersLayout.setHorizontalGroup(
            newpapersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newpapersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newpapersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                .addContainerGap())
        );
        newpapersLayout.setVerticalGroup(
            newpapersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newpapersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        KhachSan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("ĐỀ XUẤT KHÁCH SẠN TRONG KHU VỰC: ");

        danhsachHotel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        danhsachHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên khách sạn", "Giá thuê", "Đánh giá", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(danhsachHotel);

        javax.swing.GroupLayout KhachSanLayout = new javax.swing.GroupLayout(KhachSan);
        KhachSan.setLayout(KhachSanLayout);
        KhachSanLayout.setHorizontalGroup(
            KhachSanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachSanLayout.createSequentialGroup()
                .addGroup(KhachSanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhachSanLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(KhachSanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        KhachSanLayout.setVerticalGroup(
            KhachSanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachSanLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cancel_30px_1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ThoiTiet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThongTinDiaLy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newpapers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(KhachSan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ThongTinDiaLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThoiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newpapers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KhachSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         JTabbedPane tabbedPane = (JTabbedPane) SwingUtilities.getAncestorOfClass(JTabbedPane.class, PanelResult.this);
        int index = tabbedPane.indexOfComponent(PanelResult.this);
        tabbedPane.removeTabAt(index);
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KhachSan;
    private javax.swing.JPanel ThoiTiet;
    private javax.swing.JPanel ThongTinDiaLy;
    private javax.swing.JTable danhsachHotel;
    private javax.swing.JLabel danso;
    private javax.swing.JLabel doam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel newpapers;
    private javax.swing.JLabel nhietdo;
    private javax.swing.JLabel quocgia;
    private javax.swing.JLabel thoigian;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel toado;
    private javax.swing.JLabel uv;
    // End of variables declaration//GEN-END:variables
}
